const Responses = {
  books: {
    getEntities: `
<code><span class='purple'>{</span> 
    "data": <span class='purple'>[</span>
    <span class='purple'>{</span>
        id: 1,
        title: "Гарри Поттер и философский камень",
        author: "Джоан Роулинг",
        genre: "Фэнтези",
        publicationYear: 1997,
        isbn: '978-5-389-07435-4',
        pageCount: 432, 
        publisher: "Махаон",
        ageRating: '6+',
        price: 1149.00,
        description: "Гарри Поттер – сирота с необычным шрамом на лбу. 11 лет он жил в доме дяди и тёти, пока не узнал, что он – волшебник! Теперь Гарри вместе с новыми друзьями предстоит освоить магию и полёты на метле, найти таинственные крестражи и вступить в борьбу с самим Волан-де-Мортом.",
        mainCharacters: <span class='purple'>[</span>"Гарри Поттер", "Гермиона Грейнджер", "Рон Уизли"<span class='purple'>]</span>,
        scene: "Хогвартс, Англия",
        awards: <span class='purple'>[</span>"nestlé smarties book prize for 9 to 11 years"<span class='purple'>]</span>
        originalLanguage: "английский",      
        goodreadsRating: 4.50,
        tags: ["магия", "школа", "дружба"],
        movieAdaptation: true,            
        movieTitle: "Гарри Поттер и философский камень",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>,
    <span class='purple'>{</span>
        id: 2,
        title: "Властелин колец: Братство Кольца",
        author: "Дж. Р. Р. Толкин",
        genre: "Фэнтези",
        publicationYear: 1954,
        isbn: '978-5-17-081802-0',
        pageCount: 480, 
        publisher: "АСТ",
        ageRating: '12+',
        price: 549.00,
        description: "Хоббит Фродо должен уничтожить Кольцо Всевластья",
        mainCharacters: <span class='purple'>[</span>"Фродо Бэггинс", "Гэндальф", "Арагорн"<span class='purple'>]</span>,
        scene: "Средиземье",
        awards: <span class='purple'>[</span>"International Fantasy Award"<span class='purple'>]</span>,
        originalLanguage: "английский",      
        goodreadsRating: 4.40,
        tags: ["эпическое фэнтези", "приключения],
        movieAdaptation: true,            
        movieTitle: "Властелин колец: Братство Кольца",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>,           
    ...
    <span class='purple'>]</span>,
    "total": 30,
    "page": 1,
    "limit": 10,
    "totalPages": 3,
<span class='purple'>}</span>           
</code>`,
    getEntitiesQS: `
<code><span class='purple'>{</span> 
    "data": <span class='purple'>[</span>
    <span class='purple'>{</span>
        id: 6,
        title: "Убить пересмешника",
        author: "Харпер Ли",
        genre: "Роман",
        publicationYear: 1960,
        isbn: '978-5-17-104721-4',
        pageCount: 416, 
        publisher: "АСТ",
        ageRating: '12+',
        price: 799.00,
        description: "История маленького сонного городка на юге Америки, поведанная маленькой девочкой.История ее брата Джима, друга Дилла и ее отца — честного, принципиального адвоката Аттикуса Финча, одного из последних и лучших представителей старой «южной аристократии».История судебного процесса по делу чернокожего парня, обвиненного в насилии над белой девушкой.Но прежде всего — история переломной эпохи, когда ксенофобия, расизм, нетерпимость и ханжество, присущие американскому югу, постепенно уходят в прошлое.«Ветер перемен» только-только повеял над Америкой. Что он принесет?..",
        mainCharacters: <span class='purple'>[</span>"Аттикус Финч", "Скаут Финч", "Артур 'Страшила' Рэдли", "Джереми Финч"<span class='purple'>]</span>,
        scene: "Мейкомб, Алабама",
        awards: <span class='purple'>[</span>"Пулитцеровская премия(1961)", "quill award for audio book(2007)"<span class='purple'>]</span>,
        originalLanguage: "английский",      
        goodreadsRating: 4.27,
        tags: ["классика", "социальная драма"],
        movieAdaptation: true,            
        movieTitle: "Убить пересмешника",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>,
    <span class='purple'>{</span>
        id: 7,
        title: "Виноваты звезды",
        author: "Джон Грин",
        genre: "Роман",
        publicationYear: 2012,
        isbn: '978-5-17-122806-4',
        pageCount: 288, 
        publisher: "АСТ",
        ageRating: '16+',
        price: 679.00,
        description: "Подростки, страдающие от тяжелой болезни, не собираются сдаваться. Они по-прежнему остаются подростками — дерзкими, неугомонными, взрывными, бунтующими, равно готовыми и к ненависти,и к любви.Хейзел и Огастус бросают вызов судьбе.Они влюблены друг в друга, их терзает не столько нависшая над ними тень смерти, сколько обычная ревность, злость и непонимание.Они — вместе. Сейчас — вместе. Но что их ждет впереди?",
        mainCharacters: <span class='purple'>[</span>"Хейзел Грейс", "Огастус Уотерс"<span class='purple'>]</span>,
        scene: "Индианаполис, США",
        awards: <span class='purple'>[</span>"Goodreads Choice Award(2012)", "Номинация Детская премия Guardian(2013)", "Премия Kids’ Choice Awards в номинации «Любимая книга»(2015)", "Номинация Goodreads Choice Awards Best of the Best(2018)"
        <span class='purple'>]</span>,
        originalLanguage: "английский",      
        goodreadsRating: 4.29,
        tags: ["романтика", "болезнь"],
        movieAdaptation: true,            
        movieTitle: "Виноваты звезды",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>,
    <span class='purple'>{</span>
        id: 8,
        title: "451° по Фаренгейту",
        author: "Рэй Брэдбери",
        genre: "Антиутопия, научная фантастика, философский роман",
        publicationYear: 1953,
        isbn: '978-5-04-095054-6',
        pageCount: 256, 
        publisher: "Эксмо",
        ageRating: '16+',
        price: 349.00,
        description: "451° по Фаренгейту — температура, при которой воспламеняется и горит бумага. Философская антиутопия Брэдбери рисует беспросветную картину развития постиндустриального общества: это мир будущего, в котором все письменные издания безжалостно уничтожаются специальным отрядом пожарных, хранение книг преследуется по закону, интерактивное телевидение успешно служит всеобщему оболваниванию, карательная психиатрия решительно разбирается с редкими инакомыслящими, а на охоту за неисправимыми диссидентами выходит электрический пес…",
        mainCharacters: <span class='purple'>[</span>"Гай Монтэг", "Кларисса"<span class='purple'>]</span>,
        scene: "Будущее. США",
        awards: <span class='purple'>[</span>"Премия Американской академии искусств и литературы в области литературы(1954)", "Золотая медаль Калифорнийского клуба Содружества(1954)", "Премия «Прометей» в Зале славы(1984)", "Премия «Хьюго»(2004)", "Премия «Ретро-Хьюго»", "Номинация на «Грэмми» аудиокнига(1976)"<span class='purple'>]</span>,
        originalLanguage: "английский",      
        goodreadsRating: 4.04,
        tags: ["дистопия", "цензура"],
        movieAdaptation: true,            
        movieTitle: "451° по Фаренгейту",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>,   
    <span class='purple'>{</span>
        id: 9,
        title: "Над пропастью во ржи",
        author: "Джером Сэлинджер",
        genre: "Роман",
        publicationYear: 1951,
        isbn: '978-5-699-30534-6',
        pageCount: 336, 
        publisher: "Эксмо",
        ageRating: '12+',
        price: 343.00,
        description: "Над пропастью во ржи" — это громкий протест против взрослого мира, роман, воплотивший стремления к большему, искреннему, настоящему. Книга Дж. Д. Сэлинджера повествует о нескольких днях из жизни американского подростка Холдена Колфилда, чье имя уже стало символом юношеского бунтарства. Оказавший колоссальное влияние не только на литературу, но и на всю культуру конца XX и начала XXI веков, этот роман навсегда останется в коллективном сознании ярким глотком бесшабашной юности.",
        mainCharacters: <span class='purple'>[</span>"Холден Колфилд", "Стрэдлейтер", "Мистер Анатолин", "Салли Хейс"<span class='purple'>]</span>,
        scene: "Нью-Йорк, США",
        awards: <span class='purple'>[</span>"Национальная книжная премия в номинации 'Художественная литература'"<span class='purple'>]</span>,
        originalLanguage: "английский",      
        goodreadsRating: 4.08,
        tags: ["классика", "бунт"],
        movieAdaptation: true,            
        movieTitle: "За пропастью во ржи",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>,
    <span class='purple'>{</span>
        id: 10,
        title: "Шестерка воронов",
        author: "Ли Бардуго",
        genre: "Фэнтези",
        publicationYear: 2015,
        isbn: '978-5-17-108154-6',
        pageCount: 576, 
        publisher: "АСТ",
        ageRating: '18+',
        price: 849.00,
        description: "Каз Бреккер никогда не снимает черных перчаток. Но, если не хочешь стать ужином для акул, не спрашивай его, почему. Никому не известно, где его семья, откуда он пришел и почему остался в Кеттердаме. Зато он знает обо всех и все. Бреккер — правая рука главаря одной из самых влиятельных банд в городе. Казино, бордели, нелегальная торговля — его стихия. А еще шантаж, грабеж и, если понадобится, хладнокровное убийство. Но все это мелочи по сравнению с новым заказом. На кону — баснословные деньги и... секрет, который может уничтожить одни народы и возвеличить другие. Какие именно — теперь зависит от Каза и его команды. Шестерых «воронов», которым нечего терять кроме надежды. Это дело объединит их. Лучшего стрелка банды Отбросов и новичка, который не умеет держать пистолет в руках. Соблазнительную чародейку, умеющую с помощью магии взрывать сердца, и безжалостного охотника на таких, как она. Юную гимнастку из самого известного публичного дома во всей Керчии и Каза Бреккера, способного без тени сомнения вырвать глаз предателю. Им предстоит один путь, но у каждого своя цель...",
        mainCharacters: <span class='purple'>[</span>"Каз Бреккер", "Инеж Гафа", "Джеспер Файи", "Нина Зеник"<span class='purple'>]</span>,
        scene: "Вымышленный город - Кеттердам",
        awards: <span class='purple'>[</span>"Премия «Выбор читателей» на Goodreads(2015)", "Премия 'Парящий орёл'(2017)", "Премия конвента ДрагонКон(2016)"<span class='purple'>]</span>,
        originalLanguage: "английский",      
        goodreadsRating: 4.70,
        tags: ["магия", "преступность"],
        movieAdaptation: true,            
        movieTitle: "Шестерка воронов",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>
    <span class='purple'>]</span>,
    "total": 30,
    "page": 2,
    "limit": 5,
    "totalPages": 6,
<span class='purple'>}</span>           
</code>`,
    getSingleEntity: `
<code><span class='purple'>{</span>    
    id: 2,
    title: "Властелин колец: Братство Кольца",
    author: "Дж. Р. Р. Толкин",
    genre: "Фэнтези",
    publicationYear: 1954,
    isbn: '978-5-17-081802-0',
    pageCount: 480, 
    publisher: "АСТ",
    ageRating: '12+',
    price: 549.00,
    description: "Хоббит Фродо должен уничтожить Кольцо Всевластья",
    mainCharacters: <span class='purple'>[</span>"Фродо Бэггинс", "Гэндальф", "Арагорн"<span class='purple'>]</span>,
    scene: "Средиземье",
    awards: <span class='purple'>[</span>"International Fantasy Award"<span class='purple'>]</span>,
    originalLanguage: "английский",      
    goodreadsRating: 4.40,
    tags: ["эпическое фэнтези", "приключения],
    movieAdaptation: true,            
    movieTitle: "Властелин колец: Братство Кольца",
    lastUpdated : "2025-10-22",    
<span class='purple'>}</span>
</code>`,
    getSearchedEntity: `
<code><span class='purple'>{</span>
    data: <span class='purple'>[</span> 
    <span class='purple'>{</span>
        id: 1,
        title: "Гарри Поттер и философский камень",
        author: "Джоан Роулинг",
        genre: "Фэнтези",
        publicationYear: 1997,
        isbn: '978-5-389-07435-4',
        pageCount: 432, 
        publisher: "Махаон",
        ageRating: '6+',
        price: 1149.00,
        description: "Гарри Поттер – сирота с необычным шрамом на лбу. 11 лет он жил в доме дяди и тёти, пока не узнал, что он – волшебник! Теперь Гарри вместе с новыми друзьями предстоит освоить магию и полёты на метле, найти таинственные крестражи и вступить в борьбу с самим Волан-де-Мортом.",
        mainCharacters: <span class='purple'>[</span>"Гарри Поттер", "Гермиона Грейнджер", "Рон Уизли"<span class='purple'>]</span>,
        scene: "Хогвартс, Англия",
        awards: <span class='purple'>[</span>"nestlé smarties book prize for 9 to 11 years"<span class='purple'>]</span>
        originalLanguage: "английский",      
        goodreadsRating: 4.50,
        tags: ["магия", "школа", "дружба"],
        movieAdaptation: true,            
        movieTitle: "Гарри Поттер и философский камень",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>,
    <span class='purple'>{</span>
        id: 2,
        title: "Властелин колец: Братство Кольца",
        author: "Дж. Р. Р. Толкин",
        genre: "Фэнтези",
        publicationYear: 1954,
        isbn: '978-5-17-081802-0',
        pageCount: 480, 
        publisher: "АСТ",
        ageRating: '12+',
        price: 549.00,
        description: "Хоббит Фродо должен уничтожить Кольцо Всевластья",
        mainCharacters: <span class='purple'>[</span>"Фродо Бэггинс", "Гэндальф", "Арагорн"<span class='purple'>]</span>,
        scene: "Средиземье",
        awards: <span class='purple'>[</span>
            "International Fantasy Award"
        <span class='purple'>]</span>,
        originalLanguage: "английский",      
        goodreadsRating: 4.40,
        tags: ["эпическое фэнтези", "приключения],
        movieAdaptation: true,            
        movieTitle: "Властелин колец: Братство Кольца",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>,
    <span class='purple'>{</span>
        id: 10,
        title: "Шестерка воронов",
        author: "Ли Бардуго",
        genre: "Фэнтези",
        publicationYear: 2015,
        isbn: '978-5-17-108154-6',
        pageCount: 576, 
        publisher: "АСТ",
        ageRating: '18+',
        price: 849.00,
        description: "Каз Бреккер никогда не снимает черных перчаток. Но, если не хочешь стать ужином для акул, не спрашивай его, почему. Никому не известно, где его семья, откуда он пришел и почему остался в Кеттердаме. Зато он знает обо всех и все. Бреккер — правая рука главаря одной из самых влиятельных банд в городе. Казино, бордели, нелегальная торговля — его стихия. А еще шантаж, грабеж и, если понадобится, хладнокровное убийство. Но все это мелочи по сравнению с новым заказом. На кону — баснословные деньги и... секрет, который может уничтожить одни народы и возвеличить другие. Какие именно — теперь зависит от Каза и его команды. Шестерых «воронов», которым нечего терять кроме надежды. Это дело объединит их. Лучшего стрелка банды Отбросов и новичка, который не умеет держать пистолет в руках. Соблазнительную чародейку, умеющую с помощью магии взрывать сердца, и безжалостного охотника на таких, как она. Юную гимнастку из самого известного публичного дома во всей Керчии и Каза Бреккера, способного без тени сомнения вырвать глаз предателю. Им предстоит один путь, но у каждого своя цель...",
        mainCharacters: <span class='purple'>[</span>"Каз Бреккер", "Инеж Гафа", "Джеспер Файи", "Нина Зеник"
        <span class='purple'>]</span>,
        scene: "Вымышленный город - Кеттердам",
        awards: <span class='purple'>[</span>
        "Премия «Выбор читателей» на Goodreads(2015)", "Премия 'Парящий орёл'(2017)", "Премия конвента ДрагонКон(2016)"    
        <span class='purple'>]</span>,
        originalLanguage: "английский",      
        goodreadsRating: 4.70,
        tags: ["магия", "преступность"],
        movieAdaptation: true,            
        movieTitle: "Шестерка воронов",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>
    <span class='purple'>]</span>,
    "total": 3,
    "page": 1,
    "limit": 3,
    "totalPages": 1,
<span class='purple'>}</span>
</code>`,
    addEntity: `
<code> // Код ответа: <span class='success'>201</span>.

<strong class='purple'>{</strong>    
    id: '36',        
    title: "Гений",<span class="danger">// required</span>                
    author: "Теодор Драйзер",<span class="danger">// required</span>
    genre: 'роман',<span class="danger">// required</span>
    publicationYear: 1915,
    isbn: "978-5-04-198799-2",
    pageCount: 1110, 
    description: "Герой романа 'Гений', талантливый художник Юджин Витла, во многом сродни своему создателю – американскому писателю Теодору Драйзеру. Их сближают не только биографические совпадения, но и эстетические взгляды.",
    tags: <span class='purple'>[</span>"Американская классика", "Зарубежная классика", "Судьба человека"<span class='purple'>]</span>,                        
    originalLanguage: "английский",        
<strong class='purple'>}</strong>
</code>`,
    deleteEntity: `
<code> // Код ответа: <span class='success'>200</span>.

<strong class='purple'>{</strong>
    deletedEntity: 
    <span class='purple'>{</span>
        id: 6,
        title: "Убить пересмешника",
        author: "Харпер Ли",
        genre: "Роман",
        publicationYear: 1960,
        isbn: '978-5-17-104721-4',
        pageCount: 416, 
        publisher: "АСТ",
        ageRating: '12+',
        price: 799.00,
        description: "История маленького сонного городка на юге Америки, поведанная маленькой девочкой.История ее брата Джима, друга Дилла и ее отца — честного, принципиального адвоката Аттикуса Финча, одного из последних и лучших представителей старой «южной аристократии».История судебного процесса по делу чернокожего парня, обвиненного в насилии над белой девушкой.Но прежде всего — история переломной эпохи, когда ксенофобия, расизм, нетерпимость и ханжество, присущие американскому югу, постепенно уходят в прошлое.«Ветер перемен» только-только повеял над Америкой. Что он принесет?..",
        mainCharacters: <span class='purple'>[</span>"Аттикус Финч", "Скаут Финч", "Артур 'Страшила' Рэдли", "Джереми Финч"<span class='purple'>]</span>,
        scene: "Мейкомб, Алабама",
        awards: <span class='purple'>[</span>
        "Пулитцеровская премия(1961)", "quill award for audio book(2007)"
        <span class='purple'>]</span>,
        originalLanguage: "английский",      
        goodreadsRating: 4.27,
        tags: ["классика", "социальная драма"],
        movieAdaptation: true,            
        movieTitle: "Убить пересмешника",
        lastUpdated : "2025-10-22",
    <span class='purple'>}</span>,
<strong class='purple'>}</strong>
</code>`,
  },
  athletes: {
    getEntities: `
<code><span class='purple'>{</span> 
    "data": <span class='purple'>[</span>
        <span class='purple'>{</span>
            id: 1,
            fullName: "Лионель Месси",
            sport: "Футбол",
            country: 'Аргентина',
            age: 38,
            birthPlace: 'Росарио, Аргентина',
            birthDate: '1987-06-24',
            zodiacSign: 'Рак',
            gender: "мужской",
            height: 170,
            nationality: 'Аргентинец',
            position: 'Нападающий',
            currentTeam: 'Интер Майами, Сборная Аргентины по футболу',
            mainAchievements: <span class='purple'>[</span>"8 Золотых мячей", "6 золотых бутс", "Чемпион мира 2022", "4 Лиги Чемпионов УЕФА", "Президентская медаль Свободы"<span class='purple'>]</span>,          
            annualSalary: 53321240.00,
            instagramFollowers: 507718702,
            olympics: 'Золото 2008 Пекин',
            brandAmbassador: 'Adidas, Michelob Ultra, Sayyar, Huawei',
            firstVictory: 'Чемпионат мира U-20 2005',
            hobbies: 'Теннис, баскетбол, американский футбол, видеоигры, падел',
            isActive: true,  
            lastUpdated: '2025-10-25',
        <span class='purple'>}</span>,
        <span class='purple'>{</span>
            id: 2,
            fullName: "Криштиану Роналду",
            sport: "Футбол",
            country: 'Португалия',
            age: 40,
            birthPlace: 'Фуншал, Мадейра',
            birthDate: '1985-02-05',
            zodiacSign: 'Водолей',
            gender: "мужской",
            height: 187,
            nationality: 'Португалец',
            position: 'Нападающий',
            currentTeam: 'Аль-Наср, Сборная Португалии по футболу',
            mainAchievements: <span class='purple'>[</span>"5 Золотых мячей", "5 Лиг Чемпионов УЕФА", "Лучший бомбардир в истории футбола", "Победитель Евро-2016"<span class='purple'>]</span>,          
            annualSalary: 208400000.00,
            instagramFollowers: 667000000,
            olympics: '2004 Афины',
            brandAmbassador: 'Nike, Herbalife, Tag Heuer, Clear, American Tourister, Emirates, SIXPAD, Binance',
            firstVictory: 'Кубок Португалии 2003 со Спортингом',
            hobbies: 'Бильярд, картинг, падел, ходить в кино, петь',
            isActive: true,  
            lastUpdated: '2025-10-25',
        <span class='purple'>}</span>       
        ...
    <span class='purple'>]</span>,
    "total": 28,
    "page": 1,
    "limit": 10,
    "totalPages": 3,
<span class='purple'>}</span>           
</code>`,
    getEntitiesQS: `
<code><span class='purple'>{</span> 
    "data": <span class='purple'>[</span>
        <span class='purple'>{</span>
            id: 6,
            fullName: "Новак Джокович",
            sport: "Теннис",
            country: 'Сербия',
            age: 38,
            birthPlace: 'Белград, Сербия',
            birthDate: '1987-05-22',
            zodiacSign: 'Близнецы',
            gender: "мужской",
            height: 188,
            nationality: 'Серб',
            position: 'shooting guard',
            currentTeam: null,
            mainAchievements: <span class='purple'>[</span>"24 титула Большого шлема", "100 побед на турнирах АТР", "10 побед на Australian Open", "40 титулов на «Мастерсах»", "7 побед на Уимблдоне"<span class='purple'>]</span>,          
            annualSalary: 32000000.00,
            instagramFollowers: 16e6,
            olympics: 'Бронза 2008 Пекин, Лондон 2012, Рио-де-Жанейро 2016, золото Париж 2024',
            brandAmbassador: 'Lacoste, Hublot, Aman Resorts, Qatar Airways, Joe & The Juice',
            firstVictory: 'Первый титул ATP 2006 в Амерсфорте',
            hobbies: 'Походы, бег, плавание, велосипедные прогулки, футбол, баскетбол',
            isActive: true, 
            lastUpdated: '2025-10-28',
        <span class='purple'>}</span>,
        <span class='purple'>{</span>
            id: 7,
            fullName: "Карлос Алькарас",
            sport: "Теннис",
            country: 'Испания',
            age: 22,
            birthPlace: 'Эль-Пальмар, Испания',
            birthDate: '2003-05-05',
            zodiacSign: 'Телец',
            gender: "мужской",
            height: 183,
            nationality: 'Испанец',
            position: 'shooting guard',
            currentTeam: null,
            mainAchievements: <span class='purple'>[</span>"6 титулов Большого шлема", "Самый молодой №1 в истории", "Победитель 23-24 турниров ATP-тура в одиночном разряде"<span class='purple'>]</span>,          
            annualSalary: 42000000.00,
            instagramFollowers: 8000000,
            olympics: 'Серебро 2024 Париж',
            brandAmbassador: 'Louis Vuitton, Nike, Rolex, BMW, Evian, OIKOS, Calvin Klein, Babolat, Itau Unibanco',
            firstVictory: 'Первый титул ATP 2021 Хорватия',
            hobbies: 'Гольф, рыбалка, шахматы',
            isActive: true, 
            lastUpdated: '2025-10-28',
        <span class='purple'>}</span>,   
        <span class='purple'>{</span>
            id: 8,
            fullName: "Патрик Махоумс",
            sport: "Американский футбол",
            country: 'США',
            age: 30,
            birthPlace: 'Тайлер, Техас',
            birthDate: '1995-09-17',
            zodiacSign: 'Дева',
            gender: "мужской",
            height: 188,
            nationality: 'Американец',
            position: 'Квотербек',
            currentTeam: 'Канзас-Сити Чифс',
            mainAchievements: <span class='purple'>[</span>"3-кратный чемпион Супербоула", "2-кратный MVP НФЛ", "3-кратынй MVP Супербоула", "Участие 5 раз в Pro Bowl"<span class='purple'>]</span>,          
            annualSalary: 67000000.00,
            instagramFollowers: 7000000,
            olympics: null,
            brandAmbassador: 'Hublot, Throne Sport Coffee',
            firstVictory: 'НФЛ 2017',
            hobbies: 'Гольф, пинг-понг видеоигры',
            isActive: true, 
            lastUpdated: '2025-10-28',
        <span class='purple'>}</span>,
        <span class='purple'>{</span>
            id: 9,
            fullName: "Сауль Альварес",
            sport: "Бокс",
            country: 'Мексика',
            age: 35,
            birthPlace: 'Гвадалахара, Мексика',
            birthDate: '1990-07-18',
            zodiacSign: 'Рак',
            gender: "мужской",
            height: 171,
            nationality: 'Мексиканец',
            position: 'shooting guard',
            currentTeam: null,
            mainAchievements: <span class='purple'>[</span>"Чемпион мира в 4 весовых категориях", "Абсолютный чемпион мира во втором среднем весе", "63 победы", "Чемпионский пояс"<span class='purple'>]</span>,          
            annualSalary: 95000000.00,
            instagramFollowers: 19000000,
            olympics: null,
            brandAmbassador: 'No Boxing No Life, DAZN',
            firstVictory: '29 октября 2005 противник: Абрахам Гонсалес',
            hobbies: 'Гольф, автомобили и мотоциклы',
            isActive: true, 
            lastUpdated: '2025-10-30',
        <span class='purple'>}</span>,
        <span class='purple'>{</span>
            id: 10,
            fullName: "Тайгер Вудс",
            sport: "Гольф",
            country: 'США',
            age: 49,
            birthPlace: 'Сайпресс, Калифорния',
            birthDate: '1975-12-30',
            zodiacSign: 'Козерог',
            gender: "мужской",
            height: 185,
            nationality: 'Американец',
            position: null,
            currentTeam: null,
            mainAchievements: <span class='purple'>[</span>"15 титулов мейджора", "82 победы на PGA Tour", "Самый молодой победитель Мастерс 1997 в возрасте 21 лет", "Удержание титулов чемпиона в четырех мейджорах одновременно 2000-2001"<spanclass='purple'>]</span>,          
            annualSalary: 60000000.00,
            instagramFollowers: 4000000,
            olympics: null,
            brandAmbassador: 'TaylorMade, Bridgestone, Rolex',
            firstVictory: "Первая победа в PGA Tour 1997",
            hobbies: 'Гольф',
            isActive: true, 
            lastUpdated: '2025-10-30',
        <span class='purple'>}</span>
    <span class='purple'>]</span>,
    "total": 28,
    "page": 2,
    "limit": 5,
    "totalPages": 6,
<span class='purple'>}</span>           
</code>`,
    getSingleEntity: `
<code><span class='purple'>{</span>     
    id: 2,
    fullName: "Криштиану Роналду",
    sport: "Футбол",
    country: 'Португалия',
    age: 40,
    birthPlace: 'Фуншал, Мадейра',
    birthDate: '1985-02-05',
    zodiacSign: 'Водолей',
    gender: "мужской",
    height: 187,
    nationality: 'Португалец',
    position: 'Нападающий',
    currentTeam: 'Аль-Наср, Сборная Португалии по футболу',
    mainAchievements: <span class='purple'>[</span>"5 Золотых мячей", "5 Лиг Чемпионов УЕФА", "Лучший бомбардир в истории футбола", "Победитель Евро-2016"<span class='purple'>]</span>,          
    annualSalary: 208400000.00,
    instagramFollowers: 667000000,
    olympics: '2004 Афины',
    brandAmbassador: 'Nike, Herbalife, Tag Heuer, Clear, American Tourister, Emirates, SIXPAD, Binance',
    firstVictory: 'Кубок Португалии 2003 со Спортингом',
    hobbies: 'Бильярд, картинг, падел, ходить в кино, петь',
    isActive: true,  
    lastUpdated: '2025-10-25',   
<span class='purple'>}</span>
</code>`,
    getSearchedEntity: `
<code><span class='purple'>{</span>
    data: <span class='purple'>[</span>
    <span class='purple'>{</span>
        id: 4,
        fullName: "Леброн Джеймс",
        sport: "Баскетбол",
        country: 'США',
        age": 40,
        birthPlace: 'Акрон, Огайо',
        birthDate: '1984-12-30',
        zodiacSign: 'Козерог',
        gender: "мужской",
        height: 206,
        nationality: 'Американец',
        position: 'Легкий форвард',
        currentTeam: 'Лос-Анджелес Лейкерс',
        mainAchievements: <span class='purple'>[</span>"4-кратный чемпион НБА", "4-кратный MVP НБА", "3 олимпийских золота", "Чемпион Америки 2007", "Лучший снайпер в истории НБА"<span class='purple'>]</span>,          
        annualSalary: 46000000.00,
        instagramFollowers: 159000000,
        olympics: 'Бронза 2004 Афины, Золото 2008 Пекин, 2012 Лондон, 2024 Париж',
        brandAmbassador: 'Nike, McDonalds, Coca-Cola, Upper Deck',
        firstVictory: 'Чемпион НБА 2012',
        hobbies: 'Велосипедные прогулки, йога, пилатес, бег',
        isActive: true, 
        lastUpdated: '2025-10-25',
    <span class='purple'>}</span>,
    <span class='purple'>{</span>
        id: 5,
        fullName: "Стефен Карри",
        sport: "Баскетбол",
        country: 'США',
        age": 37,
        birthPlace: 'Акрон, Огайо',
        birthDate: '1988-03-14T00:00:00.000Z',
        zodiacSign: 'Рыба',
        gender: "мужской",
        height: 188,
        nationality: 'Американец',
        position: 'Разыгрывающий защитник',
        currentTeam: 'Голден Стэйт Уорриорз',
        mainAchievements: <span class='purple'>[</span>"4-кратный чемпион НБА", "2-кратный MVP НБА", "MVP Матча всех звёзд НБА 2022", "Лидер НБА по трёхочковым броскам за всю историю" <span class='purple'>]</span>,          
        annualSalary: 51000000,
        instagramFollowers: 58000000,
        olympics: 'Золото 2024 Париж',
        brandAmbassador: 'Under Armour, Curry Brand, Stone Island, Thirty Ink',
        firstVictory: 'Чемпионат NCAA 2008',
        hobbies: 'Гольф',
        isActive: true, 
        lastUpdated: '2025-10-25T00:00:00.000Z',
    <span class='purple'>}</span>,        
    <span class='purple'>{</span>
        id: 25,
        fullName: "Кевин Дюрант",
        sport: "Баскетбол",
        country: 'USA',
        age: 37,
        birthPlace: 'Вашингтон, США',
        birthDate: '1988-09-29',
        zodiacSign: 'Весы',
        gender: "man",
        height: 211,
        nationality: 'Афроамериканец',
        position: 'Лёгкий форвард',
        currentTeam: 'Хьюстон Рокетс',
        mainAchievements: <span class='purple'>[</span>"Чемпион НБА(2017,2018)", "MVP финала НБА (2017, 2018)", "MVP регулярного сезона НБА(2014)", "Самый результативный игрок регулярного чемпионата НБА(2010, 2011, 2012, 2014)", "Золото Чемпионат мира Турция(2010)", "Новичок года НБА(2008)"<span class='purple'>]</span>,          
        annualSalary: 87000000.00,
        instagramFollowers: 35000000,
        olympics: 'Золото: Лондон 2012, Рио 2016, Токио 2020, Париж 2024',
        brandAmbassador: 'Nike, Thirty Five Ventures',
        firstVictory: "2017 MVP финала НБА против 'Кливленд Кавальерс'",
        hobbies: 'Видеоигры, рэп, фотографии, мотоциклы',
        isActive: true, 
        lastUpdated: '2025-10-31',
    <span class='purple'>}</span>,
    <span class='purple'>{</span>
        id: 26,
        fullName: "Майкл Джордан",
        sport: "Баскетбол",
        country: 'США',
        age: 62,
        birthPlace: 'Бруклин, Нью-Йорк, США',
        birthDate: '1963-02-17T00:00:00.000Z',
        zodiacSign: 'Водолей',
        gender: "мужской",
        height: 198,
        nationality: 'Американец',
        position: 'Атакующий защитник',
        currentTeam: null,
        mainAchievements: <span class='purple'>[</span>"6-кратный чемпион НБА с командой 'Чикаго Буллз' (1991,1992,1993,1996,1997,1998)", "MVP финала НБА: 6 раз(рекорд)", "5-кратный MVP регулярного сезона НБА(1988, 1991, 1992, 1996, 1998)", "Лучший бомбардир НБА 10 раз (рекорд)", "MVP Матча всех звезд НБА 3 раза", "Член Зала славы баскетбола имени Нейсмита"<spanclass='purple'>]</span>,          
        annualSalary: 261000000.00,
        instagramFollowers: 27000000,
        olympics: 'Золото Лос-Анджелес 1984, Барселона 1992',
        brandAmbassador: 'Nike, Air Jordan, Coca-Cola Levi’s, Comme des Garçons, Wheaties',
        firstVictory: "Чемпион НБА 1991",
        hobbies: 'Гольф, рыбалка, плавание, теннис, мотоциклы, sudoku, коллекционирование',
        isActive: false, 
        lastUpdated: '2025-11-04',
    <span class='purple'>}</span>,        
    <span class='purple'>]</span>,
    "total": 4,
    "page": 1,
    "limit": 4,
    "totalPages": 1,
<span class='purple'>}</span>
</code>`,
    addEntity: `
<code> // Код ответа: <span class='success'>201</span>.

<strong class='purple'>{</strong>    
    id: 33,        
    fullName: "A.T. Reaves",<span class="danger">// required</span>
    sport: "basketball",<span class="danger">// required</span>
    country: 'USA',<span class="danger">// required</span>
    age: 27,<span class="danger">// required</span>                
    olympics: null,
    brandAmbassador: 'TravisMathew, Rigorer',
    firstVictory: '2023, Кубок НБА',
    hobbies: 'гольф, видеоигры',
    isActive: true,             
    ...
<strong class='purple'>}</strong>
</code>`,
    deleteEntity: `
<code> // Код ответа: <span class='success'>200</span>.

<strong class='purple'>{</strong>
    deletedEntity: 
    <strong class='purple'>{</strong>
        id: 6,
        fullName: "Новак Джокович",
        sport: "Теннис",
        country: 'Сербия',
        age: 38,
        birthPlace: 'Белград, Сербия',
        birthDate: '1987-05-22',
        zodiacSign: 'Близнецы',
        gender: "мужской",
        height: 188,
        nationality: 'Серб',
        position: 'shooting guard',
        currentTeam: null,
        mainAchievements: <span class='purple'>[</span>"24 титула Большого шлема", "100 побед на турнирах АТР", "10 побед на Australian Open", "40 титулов на «Мастерсах»", "7 побед на Уимблдоне"<span class='purple'>]</span>,          
        annualSalary: 32000000.00,
        instagramFollowers: 14.8e6,
        olympics: 'Бронза 2008 Пекин, Лондон 2012, Рио-де-Жанейро 2016, золото Париж 2024',
        brandAmbassador: 'Lacoste, Hublot, Aman Resorts, Qatar Airways, Joe & The Juice',
        firstVictory: 'Первый титул ATP 2006 в Амерсфорте',
        hobbies: 'Походы, бег, плавание, велосипедные прогулки, футбол, баскетбол',
        isActive: true, 
        lastUpdated: '2025-10-28',
    <strong class='purple'>}</strong>
<strong class='purple'>}</strong>
</code>`,
  },
};

export { Responses };
